// Auth
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';

export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const PASSWORD_RESET_EMAIL_SENT_SUCCESS =
  'PASSWORD_RESET_EMAIL_SENT_SUCCESS';
export const PASSWORD_RESET_EMAIL_SENT_FAIL = 'PASSWORD_RESET_EMAIL_SENT_FAIL';

export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';

export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_FAIL = 'PASSWORD_CHANGE_FAIL';

export const EMAIL_CONFIRMING = 'EMAIL_CONFIRMING';
export const EMAIL_CONFIRM_SUCCESS = 'EMAIL_CONFIRM_SUCCESS';
export const EMAIL_CONFIRM_FAIL = 'EMAIL_CONFIRM_FAIL';

// Error Handling
export const GET_ERRORS = 'GET_ERRORS';

// Messages
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
